name: healnet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_database: ^11.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/HealNet-removebg-preview.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/HealNet-removebg-preview.png"